export const browserCoreExamples = [
  "ws-agent browser status",
  "ws-agent browser start",
  "ws-agent browser stop",
  "ws-agent browser tabs",
  "ws-agent browser open https://example.com",
  "ws-agent browser focus abcd1234",
  "ws-agent browser close abcd1234",
  "ws-agent browser screenshot",
  "ws-agent browser screenshot --full-page",
  "ws-agent browser screenshot --ref 12",
  "ws-agent browser snapshot",
  "ws-agent browser snapshot --format aria --limit 200",
  "ws-agent browser snapshot --efficient",
  "ws-agent browser snapshot --labels",
];

export const browserActionExamples = [
  "ws-agent browser navigate https://example.com",
  "ws-agent browser resize 1280 720",
  "ws-agent browser click 12 --double",
  'ws-agent browser type 23 "hello" --submit',
  "ws-agent browser press Enter",
  "ws-agent browser hover 44",
  "ws-agent browser drag 10 11",
  "ws-agent browser select 9 OptionA OptionB",
  "ws-agent browser upload /tmp/ws-agent/uploads/file.pdf",
  'ws-agent browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "ws-agent browser dialog --accept",
  'ws-agent browser wait --text "Done"',
  "ws-agent browser evaluate --fn '(el) => el.textContent' --ref 7",
  "ws-agent browser console --level error",
  "ws-agent browser pdf",
];
